# Generated by Django 6.1 on 2026-08-26 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Atuador')], max_length=16)),
                ('metric', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('value_type', models.CharField(choices=[('decimal', 'Decimal'), ('boolean', 'Booleano'), ('integer', 'Inteiro'), ('text', 'Texto')], default='decimal', max_length=16)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('hardware_platform', models.CharField(blank=True, max_length=80)),
                ('capabilities', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('operator', models.CharField(choices=[('lt', 'Menor que'), ('lte', 'Menor ou igual'), ('gt', 'Maior que'), ('gte', 'Maior ou igual'), ('eq', 'Igual')], max_length=4)),
                ('threshold', models.DecimalField(decimal_places=6, max_digits=18)),
                ('severity', models.PositiveSmallIntegerField(default=2)),
                ('cooldown_seconds', models.PositiveIntegerField(default=900)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.organization')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('provisioning', 'Em provisionamento'), ('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Em manutenção'), ('retired', 'Desativado')], default='provisioning', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gardens.gardenmodule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.organization')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicemodel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.device'),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('succeeded', 'Executado'), ('failed', 'Falhou'), ('expired', 'Expirado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='devices.channel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='principal', max_length=80)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('secret_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('uptime_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('signal_strength', models.SmallIntegerField(blank=True, null=True)),
                ('free_heap_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='LightingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('days_of_week', models.JSONField(default=list, help_text='0=segunda-feira, 6=domingo')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_schedules', to='devices.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('quality', models.CharField(default='good', max_length=30)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='devices.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='open', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='devices.alertrule')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='devices.telemetryreading')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('device', 'key'), name='uniq_device_channel'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status', 'not_before'], name='devices_dev_device__d9b5d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecommand',
            constraint=models.UniqueConstraint(fields=('device', 'idempotency_key'), name='uniq_device_command'),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device', 'recorded_at'], name='devices_dev_device__fef344_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='devices_dev_organiz_c0273e_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='uniq_org_device_serial'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['channel', 'recorded_at'], name='devices_tel_channel_1d955c_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.UniqueConstraint(fields=('channel', 'idempotency_key'), name='uniq_channel_ingestion'),
        ),
    ]
