# Generated by Django 6.1 on 2026-08-27 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('default_unit', models.CharField(blank=True, max_length=24)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('boolean', 'Booleano'), ('integer', 'Inteiro'), ('text', 'Texto')], default='decimal', max_length=16)),
                ('minimum_expected', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('maximum_expected', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='source',
            field=models.CharField(choices=[('device', 'Dispositivo'), ('simulator', 'Simulador'), ('manual', 'Manual/teste'), ('import', 'Importação')], default='device', max_length=20),
        ),
        migrations.CreateModel(
            name='SensorCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibrated_at', models.DateTimeField()),
                ('reference_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('measured_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('offset', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scale_factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('next_calibration_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrations', to='devices.channel')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_calibrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='metric_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='devices.telemetrymetric'),
        ),
    ]
