# Generated by Django 6.1 on 2026-09-30 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_migrate_channel_metrics'),
        ('gardens', '0003_garden_automation_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gardens.garden'),
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('esp8266', 'Controlador ESP8266'), ('esp32_cam', 'Câmera ESP32-CAM')], default='esp8266', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GardenPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('byte_size', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='devices.device')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gardens.garden')),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['garden', 'captured_at'], name='devices_gar_garden__7d6525_idx')],
            },
        ),
    ]
