# Generated by Django 6.1 on 2026-08-26 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_name', models.CharField(max_length=120)),
                ('scientific_name', models.CharField(blank=True, max_length=180)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('days_to_harvest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivars', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=24)),
                ('minimum', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crops.cultivar')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('active', 'Ativo'), ('harvested', 'Colhido'), ('canceled', 'Cancelado')], default='planned', max_length=20)),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_harvest_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planting_cycles', to='crops.cultivar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planting_cycles', to='gardens.gardenmodule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvested_at', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('loss_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quality_notes', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='crops.plantingcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField()),
                ('observed_at', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_observations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='crops.plantingcycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cultivar',
            constraint=models.UniqueConstraint(fields=('crop', 'name'), name='uniq_crop_cultivar'),
        ),
        migrations.AddConstraint(
            model_name='croprequirement',
            constraint=models.UniqueConstraint(fields=('cultivar', 'metric'), name='uniq_cultivar_metric'),
        ),
    ]
