# Generated by Django 6.1 on 2026-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='difficulty',
            field=models.CharField(default='Fácil', max_length=30),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='light_requirement',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='crop',
            name='uses',
            field=models.TextField(blank=True),
        ),
    ]
