# Generated by Django 6.1 on 2026-08-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_fertilizer_harvestevent_substratematerial_and_more'),
        ('operations', '0004_inventorycategory_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilizers', to='operations.supplier'),
        ),
        migrations.AddField(
            model_name='cropnutritionplan',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_plans', to='crops.fertilizer'),
        ),
        migrations.AddField(
            model_name='harvestevent',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_events', to='crops.plantingcycle'),
        ),
        migrations.AddField(
            model_name='substratematerial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substrate_materials', to='operations.supplier'),
        ),
        migrations.AddConstraint(
            model_name='substraterecipe',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_substrate_recipe_version'),
        ),
        migrations.AddField(
            model_name='plantingcycle',
            name='substrate_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planting_cycles', to='crops.substraterecipe'),
        ),
        migrations.AddField(
            model_name='substraterecipecomponent',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='crops.substratematerial'),
        ),
        migrations.AddField(
            model_name='substraterecipecomponent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='crops.substraterecipe'),
        ),
        migrations.AddConstraint(
            model_name='harvestevent',
            constraint=models.UniqueConstraint(fields=('cycle', 'harvest_number'), name='uniq_cycle_harvest_number'),
        ),
    ]
