# Generated by Django 6.1 on 2026-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_fertilizer_supplier_cropnutritionplan_fertilizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcultivationprofile',
            name='automation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Regras padrão de irrigação, fertilização e iluminação.'),
        ),
    ]
