# Generated by Django 6.1 on 2026-08-26 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardens', to='accounts.address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GardenMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gardens.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('stock', 'Em estoque'), ('installed', 'Instalado'), ('maintenance', 'Em manutenção'), ('retired', 'Desativado')], default='stock', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_modules', to='accounts.organization')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='gardens.moduletype')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_label', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_installations', to='gardens.garden')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='gardens.gardenmodule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_garden_code'),
        ),
        migrations.AddConstraint(
            model_name='gardenmember',
            constraint=models.UniqueConstraint(fields=('garden', 'user'), name='uniq_garden_user'),
        ),
        migrations.AddConstraint(
            model_name='moduleinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('module',), name='uniq_active_module_install'),
        ),
        migrations.AddConstraint(
            model_name='gardenmodule',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='uniq_org_module_serial'),
        ),
    ]
