# Generated by Django 6.1 on 2026-08-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_fertilizer_harvestevent_substratematerial_and_more'),
        ('gardens', '0001_initial'),
        ('subscriptions', '0003_payment_competence_payment_discount_cents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='controller_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='garden',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='garden',
            name='grow_light_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='garden',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='location_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='garden',
            name='module_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='next_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='operational_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='pets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='position_description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='garden',
            name='primary_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garden',
            name='pump_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='garden',
            name='reservoir_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garden',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='site_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='socket_nearby',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('waiting_installation', 'Aguardando instalação'), ('installed', 'Instalada'), ('maintenance', 'Em manutenção'), ('inactive', 'Inativa')], default='planned', max_length=30),
        ),
        migrations.AddField(
            model_name='garden',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardens', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='garden',
            name='sunlight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='garden',
            name='technical_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='garden',
            name='wifi_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='wifi_quality',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='next_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='position_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='pot_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='qr_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gardenmodule',
            name='substrate_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='pot_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='recommended_crops',
            field=models.ManyToManyField(blank=True, related_name='recommended_module_types', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='substrate_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='supports_irrigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='supports_lighting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='supports_sensors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='water_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gardenmodule',
            name='status',
            field=models.CharField(choices=[('stock', 'Em estoque'), ('prepared', 'Preparado'), ('installed', 'Instalado'), ('maintenance', 'Em manutenção'), ('removed', 'Retirado'), ('discarded', 'Descartado'), ('retired', 'Desativado')], default='stock', max_length=20),
        ),
    ]
