# Generated by Django 6.1 on 2026-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_children_garden_controller_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='automation_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Exceções locais sobre a configuração padrão da cultura.'),
        ),
    ]
