# Generated by Django 6.1 on 2026-08-27 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='installation', max_length=40),
        ),
        migrations.AddField(
            model_name='address',
            name='condominium_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='has_doorman',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('commercial', 'Comercial')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
    ]
