# Generated by Django 6.1 on 2026-08-27 19:32

import uuid
from django.db import migrations, models


def ensure_unique_public_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all().iterator():
        user.public_id = uuid.uuid4()
        user.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_user_public_ids'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
