from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path("", views.home, name="home"), path("como-funciona/", views.public_page, {"page": "how-it-works"}, name="how-it-works"), path("sobre/", views.public_page, {"page": "about"}, name="about"), path("faq/", views.public_page, {"page": "faq"}, name="faq"), path("contato/", views.public_page, {"page": "contact"}, name="contact"),
    path("planos/", views.plans, name="plans"), path("planos/<slug:code>/", views.plan_detail, name="plan-detail"), path("plano/<slug:code>/", views.plan_detail), path("culturas/", views.crop_catalog, name="crop-catalog"), path("culturas/<slug:code>/", views.crop_detail, name="crop-detail"),
    path("conta/cadastro/", views.signup, name="signup"), path("conta/entrar/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"), path("conta/sair/", auth_views.LogoutView.as_view(), name="logout"),
    path("conta/recuperar/", auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", email_template_name="registration/password_reset_email.html", success_url=reverse_lazy("password_reset_done")), name="password_reset"), path("conta/recuperar/enviado/", auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"), path("conta/redefinir/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html", success_url=reverse_lazy("password_reset_complete")), name="password_reset_confirm"), path("conta/redefinir/concluido/", auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"), path("conta/destino/", views.post_login, name="post-login"),
    path("assinar/<int:step>/", views.checkout, name="checkout"), path("assinar/concluir/", views.checkout_complete, name="checkout-complete"),
    path("app/", views.customer_dashboard, name="customer-dashboard"), path("app/historico/telemetria/", views.history, name="customer-history"), path("app/dispositivo/acao/", views.device_action, name="device-action"), path("app/iluminacao/<uuid:schedule_id>/", views.lighting_schedule, name="lighting-schedule"), path("app/suporte/chamados/", views.support, name="customer-support"), path("app/perfil/editar/", views.profile, name="customer-profile"), path("app/modulos/adicionar/", views.add_module, name="add-module"), path("app/modulos/<uuid:module_id>/", views.module_detail, name="module-detail"), path("app/ciclos/<uuid:cycle_id>/trocar/", views.request_crop_change, name="request-crop-change"), path("app/<str:section>/", views.customer_section, name="customer-section"),
    path("operacao/", views.tech_dashboard, name="tech-dashboard"), path("operacao/visitas/", views.tech_visits, name="tech-visits"), path("operacao/visitas/<uuid:visit_id>/", views.visit_detail, name="visit-detail"), path("operacao/visitas/<uuid:visit_id>/atualizar/", views.visit_update, name="visit-update"),
    path("gestao/", views.ops_dashboard, name="ops-dashboard"), path("gestao/ordens/nova/", views.create_work_order, name="create-work-order"), path("gestao/<str:section>/", views.ops_collection, name="ops-collection"), path("health/", views.health, name="health"),
]
