# Generated by Django 6.1 on 2026-08-26 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_description_crop_difficulty_crop_is_available_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_data', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('canceled', 'Cancelado')], default='draft', max_length=20)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_requests', to='subscriptions.planversion')),
                ('selected_cultures', models.ManyToManyField(blank=True, related_name='checkout_requests', to='crops.cultivar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
