# Generated by Django 6.1 on 2026-08-27 19:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_access_instructions_address_access_notes_and_more'),
        ('subscriptions', '0002_checkoutrequest_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='competence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='gross_amount_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='plan',
            name='commercial_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='faq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='ideal_for',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='installation_fee_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='short_copy',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='plan',
            name='subtitle',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='planversion',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='planversion',
            name='installation_fee_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='contracted_price_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_discount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_purchase_cents', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('maximum_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('limit_per_customer', models.PositiveIntegerField(default=1)),
                ('new_customers_only', models.BooleanField(default=False)),
                ('first_charge_only', models.BooleanField(default=False)),
                ('applicable_charges', models.PositiveSmallIntegerField(default=1)),
                ('applies_to_all_plans', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_coupons', to='accounts.organization')),
                ('plans', models.ManyToManyField(blank=True, related_name='coupons', to='subscriptions.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.coupon'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.coupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount_cents', models.PositiveIntegerField()),
                ('discount_cents', models.PositiveIntegerField()),
                ('final_amount_cents', models.PositiveIntegerField()),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='subscriptions.coupon')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='accounts.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='subscriptions.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='subscriptions.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit_type', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('period', models.CharField(choices=[('once', 'Único'), ('month', 'Mensal'), ('quarter', 'Trimestral'), ('semester', 'Semestral'), ('year', 'Anual')], default='month', max_length=20)),
                ('unlimited', models.BooleanField(default=False)),
                ('carries_balance', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.planversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
