# Generated by Django 6.1 on 2026-08-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_migrate_inventory_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'verbose_name': 'categoria de estoque', 'verbose_name_plural': 'categorias de estoque'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'item de estoque', 'verbose_name_plural': 'itens de estoque'},
        ),
        migrations.AlterModelOptions(
            name='stocklot',
            options={'verbose_name': 'lote de estoque', 'verbose_name_plural': 'lotes de estoque'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'movimentação de estoque', 'verbose_name_plural': 'movimentações de estoque'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
    ]
